### ISSUE TITLE
Feature Request: Capability to add tags to VMs getting created

### ISSUE THREAD

**Issue by dumblerod** [rdvansloten/az-vm#1]
Would love to request ability to add tags when building out the VM

**Comment by rdvansloten** [comment]
Done 🙂 use variable "vm_tags" with a dict to try it.
```
vars:
  vm_tags:
    role: "webserver"
   something: "else"
```

Worked for me. Not setting the vm_tag just assigns no tags, so they're not mandatory 🙂 Tags are not applied to any of the VM children (disk, NIC, public IP), but this is according to Ansible spec.

See: https://github.com/rdvansloten/az-vm/commit/bd3877d6dba57d3361b71bef510e2fc2c094632d

I've also applied `default(omit)` to Managed Disks, SSH keys, Availability Sets. They are no longer a hard requirement, but merely a best practice. 

Can you see if this works for you @dumblerod ?

**Comment by rdvansloten** [comment]
Playbook I used with success:

```
---
- hosts: localhost
  connection: local
  vars:
    rg_name: "0000-throwaway"
    vm_name: "throwmeaway1"
    sa_name: "throwlogstorage"
    vn_name: "trash-vnet"
    vn_rg_name: "0000-throwaway"
    nsg_name: "trash-nsg"
    avset_name: "trash-avset"
    vm_size: "Standard_F2s"
    group_name: "temp"

    ssh_keys:
      - path: "/home/{{ vm_username }}/.ssh/authorized_keys"
        key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDoX8pnRUaXyfwlBPDk08bdQKyBaRnATdmzzNuJr7+nkDV2ipF1I6NWq+LXraWrwr4d587f0odhx9dL14/CYJpS/Hn2baBQ7j7XKlbpPJFycPdgzCZRv2e/lYD88FadctrUcUhnx5hGnuJqJWi$

  roles:
    - rdvansloten.az_resource_group
    - rdvansloten.az_storage_account
    - rdvansloten.az_public_ip
    - rdvansloten.az_virtual_network
    - rdvansloten.az_network_interface
    - rdvansloten.az_network_security_group
    - rdvansloten.az_vm
    - rdvansloten.az_managed_disk

- hosts: temp
  become: yes
  vars:
    ssh_user: root

  roles:
    - rdvansloten.os_mount_disk

```
